### ISSUE TITLE
What is `run_openea`?

### ISSUE THREAD

**Issue by zxC0der** [ZJU-DBL/LargeEA#2]
In main.py line 273.

```python
    if args.openea:
        from run_openea import run_openea

        try:
            result = run_openea(args, d)
        except Exception as e:
            result = str(e)
        log_information(data, lang, -1, 'OpenEA-' + args.model, args.save_prefix, result, openea=True)
        exit(0)
```

I can't find it.

**Comment by xz-liu** [comment]
This is used for some sub-experiments in the paper. We run [OpenEA](https://github.com/nju-websoft/OpenEA) to compare the scalability of different models, and this code helps us to do so. Please ignore it.
