### ISSUE TITLE
Some problems when executing LargeEA

### ISSUE THREAD

**Issue by Fino2020** [ZJU-DBL/LargeEA#3]
It's my first time to use WSL2 with GPU to execute code,and I have no idea of this Error `ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/yzl/anaconda3/envs/LargeEA/lib/python3.7/site-packages/faiss/../../../libfaiss.so)`
I searched in somewhere and their problem is not coming with `faiss`.
![image](https://user-images.githubusercontent.com/66312471/200761765-68df7254-e4ab-40c5-84a1-028261046dcb.png)

**Comment by Fino2020** [comment]
I have solved this problem 
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC` to check whether `GLIBCXX_3.4.26` exit.
then install `gcc-9` and `libstdc++6`.
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt update`
`sudo apt install gcc-9`
`sudo apt install libstdc++6`

**Comment by Fino2020** [comment]
and Another problem exited. what is this `nxmetis `package??? I can't install this package by pip and conda
![image](https://user-images.githubusercontent.com/66312471/200769364-d9a1d459-8076-42aa-a6dd-1be9a1a684ad.png)

**Comment by xz-liu** [comment]
Sorry for the late response. I am afraid that we do not have WSL environments to test this.

About the "nxmetis" package, please refer to the following:
 https://github.com/networkx/networkx-metis
